/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangeColorScheme: typeof import('./../components/ChangeColorScheme.vue')['default']
    ChangeLayoutMode: typeof import('./../components/ChangeLayoutMode/index.vue')['default']
    ChangeSize: typeof import('./../components/ChangeSize.vue')['default']
    Components: typeof import('./../components/index.vue')['default']
    FullScreen: typeof import('./../components/FullScreen.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    LangSelect: typeof import('./../components/LangSelect.vue')['default']
    Logo: typeof import('./../components/Logo.vue')['default']
    MenuSearch: typeof import('./../components/MenuSearch/index.vue')['default']
    PageFooter: typeof import('./../components/PageFooter.vue')['default']
    PageHeader: typeof import('./../components/PageHeader.vue')['default']
    Reload: typeof import('./../components/Reload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./../components/Screenfull/index.vue')['default']
    SelectColor: typeof import('./../components/ThemeSelect/coms/SelectColor.vue')['default']
    Setting: typeof import('./../components/Setting/index.vue')['default']
    SettingDrawer: typeof import('./../components/Setting/SettingDrawer/index.vue')['default']
    SidebarCollapse: typeof import('./../components/SidebarCollapse.vue')['default']
    SideBarCollapse: typeof import('./../components/SideBarCollapse.vue')['default']
    SideMenu: typeof import('./../components/SideMenu.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
    ThemeSelect: typeof import('./../components/ThemeSelect/index.vue')['default']
  }
}
